dbt_top_10_offers:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME', 'mydedb') }}"
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      # host: database-szu.cho4g6iwwuxi.eu-west-1.rds.amazonaws.com
      pass: "{{ env_var('DB_PASSWORD', 'XXXX') }}"
      port: "{{ env_var('DB_PORT', 5432)|int }}"
      schema: "{{ env_var('DB_SCHEMA', 'mw_jobs') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USERNAME', 'deuser') }}"
  target: dev
