dbt_top_10_offers:
  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('DB_NAME', 'demp_mw') }}"
      host: "{{ env_var('DB_HOST', 'demp-lm.cbgcswyss32m.eu-central-1.rds.amazonaws.com') }}"
      pass: "{{ env_var('DB_PASSWORD', 'XXXX') }}"
      port: "{{ env_var('DB_PORT', 5432)|int }}"
      schema: "{{ env_var('DB_SCHEMA', 'mw_jobs') }}"
      user: "{{ env_var('DB_USERNAME', 'demp_mw_dbt_user') }}"
      threads: 1
  target: dev

elementary:
  outputs:
    default:
      type: "postgres"
      host: "{{ env_var('DB_HOST', 'demp-lm.cbgcswyss32m.eu-central-1.rds.amazonaws.com') }}"
      port: "{{ env_var('DB_PORT', 5432)|int }}"
      user:  "{{ env_var('DB_USERNAME', 'demp_mw_dbt_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'XXXX') }}"
      dbname: "{{ env_var('DB_NAME', 'demp_mw') }}"
      schema: "{{ env_var('DB_ELEMENTARY_SCHEMA', 'mw_jobs_elementary') }}"
      threads: 1
